version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data
    environment:
      MYSQL_DATABASE: chatcleverse
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: hanwha
    networks:
      - ccl-network
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-data
    environment:
      - MONGO_INITDB_DATABASE=chatcleverse
    command: [ "--bind_ip", "0.0.0.0" ]
    networks:
      - ccl-network


  application:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.1:3306/chatcleverse?serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "hanwha"
    depends_on:
      - mysql
      - mongodb
    networks:
      - ccl-network

volumes:
  db-data:

networks:
  ccl-network:
